In [1]:
import pandas as pd

In [2]:
from pathlib import Path

csv_path = Path("../../data/raw")
csv_splits = ["partition1", "partition2", "partition3", "partition4", "partition5"]
classes = ["FL", "NF"]

# numCSV = {"FL": 0, "NF": 0}

for s in csv_splits:
    for c in classes:
        path = csv_path / s / c
        print(s, c, len(list(path.glob("*.csv"))))
        # numCSV[c] += len(list(path.glob("*.csv")))

partition1 FL 1254
partition1 NF 72238
partition2 FL 0
partition2 NF 0
partition3 FL 1424
partition3 NF 41086
partition4 FL 1165
partition4 NF 50096
partition5 FL 0
partition5 NF 0

In [6]:
# viewFeat = csv_path / "partition3 / "FL"
# sample = next(viewFeat.glob("*.csv"))
# df_test = pd.read_csv(sample, sep="\t")

In [4]:
df_test.columns
# df.shape

Index(['Timestamp', 'TOTUSJH', 'TOTBSQ', 'TOTPOT', 'TOTUSJZ', 'ABSNJZH',
       'SAVNCPP', 'USFLUX', 'TOTFZ', 'MEANPOT', 'EPSZ', 'MEANSHR', 'SHRGT45',
       'MEANGAM', 'MEANGBT', 'MEANGBZ', 'MEANGBH', 'MEANJZH', 'TOTFY',
       'MEANJZD', 'MEANALP', 'TOTFX', 'EPSY', 'EPSX', 'R_VALUE', 'CRVAL1',
       'CRLN_OBS', 'CRLT_OBS', 'CRVAL2', 'HC_ANGLE', 'SPEI', 'LAT_MIN',
       'LON_MIN', 'LAT_MAX', 'LON_MAX', 'QUALITY', 'BFLARE', 'BFLARE_LABEL',
       'CFLARE', 'CFLARE_LABEL', 'MFLARE', 'MFLARE_LABEL', 'XFLARE',
       'XFLARE_LABEL', 'BFLARE_LOC', 'BFLARE_LABEL_LOC', 'CFLARE_LOC',
       'CFLARE_LABEL_LOC', 'MFLARE_LOC', 'MFLARE_LABEL_LOC', 'XFLARE_LOC',
       'XFLARE_LABEL_LOC', 'XR_MAX', 'XR_QUAL', 'IS_TMFI'],
      dtype='object')

In [5]:
df_test.head(1)

,Timestamp,TOTUSJH,TOTBSQ,TOTPOT,TOTUSJZ,ABSNJZH,SAVNCPP,USFLUX,TOTFZ,MEANPOT,...,BFLARE_LABEL_LOC,CFLARE_LOC,CFLARE_LABEL_LOC,MFLARE_LOC,MFLARE_LABEL_LOC,XFLARE_LOC,XFLARE_LABEL_LOC,XR_MAX,XR_QUAL,IS_TMFI
0,2010-08-07 03:36:00,909.052634,1.430526e+10,2.314318e+23,1.883244e+13,130.069909,1.020244e+12,1.537751e+22,-5.431882e+24,6980.096952,...,NaN,0.0,NaN,0.0,NaN,0.0,NaN,2.131800e-07,12,True

In [6]:
df_test.isnull().sum().sort_values(ascending=False).head(10)

CFLARE_LABEL_LOC    60
MFLARE_LABEL_LOC    60
BFLARE_LABEL        60
MFLARE_LABEL        60
XFLARE_LABEL        60
BFLARE_LABEL_LOC    60
CFLARE_LABEL        60
XFLARE_LABEL_LOC    60
LAT_MAX              0
CFLARE               0
dtype: int64

In [7]:
from pathlib import Path
import pandas as pd


new_path = Path("../../data/raw")
split =  "partition3"
classes = ["FL", "NF"]

row_counts = []

for c in classes:
    folder = new_path / split / c
    for f in folder.glob("*.csv"):
        df = pd.read_csv(f, sep="\t")
        row_counts.append(len(df))

In [8]:
import numpy as np

row_counts = np.array(row_counts)

print("Total samples: ", len(row_counts))
print("Unique number of rows in csv's:", np.unique(row_counts))
# print("Min length:", row_counts.min())
# print("Max length:", row_counts.max())

Total samples:  42510
Unique number of rows in csv's: [60]

In [9]:
containsWords = ["FLARE", "LOC", "LABEL", "Timestamp"]

testDrop = []

for col in df.columns:
    for word in containsWords:
        if word in col:
            testDrop.append(col)
            break

row_df = df.drop(columns=testDrop)

In [10]:
print(row_df.shape)

(60, 38)

In [11]:
row_df.dtypes

TOTUSJH     float64
TOTBSQ      float64
TOTPOT      float64
TOTUSJZ     float64
ABSNJZH     float64
SAVNCPP     float64
USFLUX      float64
TOTFZ       float64
MEANPOT     float64
EPSZ        float64
MEANSHR     float64
SHRGT45     float64
MEANGAM     float64
MEANGBT     float64
MEANGBZ     float64
MEANGBH     float64
MEANJZH     float64
TOTFY       float64
MEANJZD     float64
MEANALP     float64
TOTFX       float64
EPSY        float64
EPSX        float64
R_VALUE     float64
CRVAL1      float64
CRLN_OBS    float64
CRLT_OBS    float64
CRVAL2      float64
HC_ANGLE    float64
SPEI           bool
LAT_MIN     float64
LON_MIN     float64
LAT_MAX     float64
LON_MAX     float64
QUALITY     float64
XR_MAX      float64
XR_QUAL       int64
IS_TMFI        bool
dtype: object

In [12]:
df[['BFLARE_LABEL', 'CFLARE_LOC', 'MFLARE', 'XFLARE']].head(20)


# quick_df[['BFLARE_LABEL', 'CFLARE_LOC', 'MFLARE', 'XFLARE']].head(80)

    BFLARE_LABEL  CFLARE_LOC  MFLARE  XFLARE
0            NaN         0.0     0.0     0.0
1            NaN         0.0     0.0     0.0
2            NaN         0.0     0.0     0.0
3            NaN         0.0     0.0     0.0
4            NaN         0.0     0.0     0.0
5            NaN         0.0     0.0     0.0
6            NaN         0.0     0.0     0.0
7            NaN         0.0     0.0     0.0
8            NaN         0.0     0.0     0.0
9            NaN         0.0     0.0     0.0
10           NaN         0.0     0.0     0.0
11           NaN         0.0     0.0     0.0
12           NaN         0.0     0.0     0.0
13           NaN         0.0     0.0     0.0
14           NaN         0.0     0.0     0.0
15           NaN         0.0     0.0     0.0
16           NaN         0.0     0.0     0.0
17           NaN         0.0     0.0     0.0
18           NaN         0.0     0.0     0.0
19           NaN         0.0     0.0     0.0

In [13]:
# def classifyIntensity(sample):
#     if sample.startswith("B"):
#         return "B"
#     if sample.startswith("C"):
#         return "C"
#     if sample.startswith("M"):
#         return "M"
#     if sample.startswith("X"):
#         return "X"
#     else:
#         return "NF"

def classifyIntensity(sample):
    if sample.startswith("M") or sample.startswith("X"):
        return 1
    else:
        # weak flare (B,C,NF) 
        return 0

In [14]:
def extract_ar(file):
    sections = file.split('_')
    for section in sections:
        if section.startswith("ar"):
            return section
    return None

In [15]:
print(df.shape)
# print(classifyIntensity(csv_file.name))

(60, 55)

In [14]:
# from pathlib import Path
# import pandas as pd
# import numpy as np

# X = []
# y = []

# for c in classes:
#     folder = new_path / split/ c
    
#     for csv_samples in folder.glob("*.csv"):
#         df = pd.read_csv(csv_samples, sep="\t")

#         new_df = df.drop(columns=dropColumns)

#         X.append(new_df.values)
#         y.append(classifyIntensity(csv_samples.name))

# X = np.array(X)
# y = np.array(y)

In [16]:
# shapes = [arr.shape for arr in X]
# print(set(shapes))

In [ ]:
from pathlib import Path
import pandas as pd
import numpy as np

X = []
y = []
regions = []

for c in classes:
    folder = new_path / split/ c
    
    for csv_samples in folder.glob("*.csv"):
        df = pd.read_csv(csv_samples, sep="\t")

        containsWords = ["FLARE", "LOC", "LABEL", "Timestamp"]

        dropColumns = []

        for col in df.columns:
            for word in containsWords:
                if word in col:
                    dropColumns.append(col)
                    break

        new_df = df.drop(columns=dropColumns)

        X.append(new_df.values)
        y.append(classifyIntensity(csv_samples.name))
        regions.append(extract_ar(csv_samples.name))

X = np.array(X)
y = np.array(y)
regions = np.array(regions)

In [17]:
print(X.shape)
print(np.unique(y, return_counts=True))

(42510, 60, 38)
(array([0, 1]), array([41086,  1424]))

In [18]:
print(regions.shape)
print(regions)

(42510,)
['ar3497' 'ar3688' 'ar4186' ... 'ar4093' 'ar3563' 'ar3907']

In [26]:
# np.save("../../data/savedData/X_data.npy", X)
# np.save("../../data/savedData/y_data.npy", y)
# np.save("../../data/savedData/regions.npy", regions)

In [19]:
np.save("../../data/savedData/X_partition3.npy", X)
np.save("../../data/savedData/y_partition3.npy", y)
np.save("../../data/savedData/regions_partition3.npy", regions)